# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-26 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_courseorg_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='click_num',
            new_name='click_nums',
        ),
    ]
