# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-27 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20170427_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='announcement',
            field=models.CharField(default='', max_length=50, verbose_name='\u8bfe\u7a0b\u516c\u544a'),
        ),
    ]
